# Generated by Django 3.2.8 on 2023-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='Duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(blank=True, default='2026-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
