# Generated by Django 3.2.8 on 2021-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_auto_20211010_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
