# Generated by Django 3.2.8 on 2021-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_remove_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
