# Generated by Django 3.2.8 on 2021-10-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_remove_task_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManager.task'),
        ),
    ]
