# Generated by Django 3.2.8 on 2021-10-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0006_task_subtask'),
        ('taskManager', '0007_auto_20211017_1809'),
    ]

    operations = [
    ]
