# Generated by Django 3.2.8 on 2021-10-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0008_merge_0006_task_subtask_0007_auto_20211017_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.RemoveField(
            model_name='task',
            name='summary',
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
