# Generated by Django 3.2.8 on 2021-10-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0011_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[('Not Started', 1), ('In Progress', 2), ('Testing', 3), ('Done', 4)], default='Not Started'),
        ),
    ]
