# Generated by Django 3.2.8 on 2021-10-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Testing'), (4, 'Done')], default=1),
        ),
    ]
