# Generated by Django 3.2.8 on 2021-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0014_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('progress', 'Progress'), ('review', 'Review'), ('done', 'Done')], max_length=30),
        ),
    ]
