# Generated by Django 3.2.8 on 2021-10-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0015_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField(unique=True)),
                ('Duration', models.DurationField()),
                ('end', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Progress', 'Progress'), ('Review', 'Review'), ('Done', 'Done')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManager.sprint'),
        ),
    ]
