# Generated by Django 3.2.8 on 2021-10-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0018_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Progress', 'Progress'), ('Review', 'Review'), ('Done', 'Done')], max_length=30),
        ),
    ]
