# Generated by Django 3.2.8 on 2021-11-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0021_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('Progress', 'Progress'), ('Review', 'Review'), ('Done', 'Done')], default='Todo', max_length=30),
        ),
    ]
