# Generated by Django 3.2.8 on 2021-11-03 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0024_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='projectname',
            field=models.ForeignKey(default='', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='taskManager.project'),
        ),
    ]
