# Generated by Django 3.2.8 on 2021-11-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0027_auto_20211105_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['projectname']},
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskManager.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='projectname',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManager.project'),
        ),
    ]
