# Generated by Django 3.2.8 on 2021-11-05 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0028_auto_20211105_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['project']},
        ),
    ]
